### ISSUE TITLE
circular structure to JSON

### ISSUE THREAD

**Issue by mjpitz** [depscloud/extractor#67]
Stumbled on this today. While the log.trace isn't being output, the string interpolation on that line still happens. We should just remove that line.

```
extractor_1  | (node:17) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
extractor_1  |     at JSON.stringify (<anonymous>)
extractor_1  |     at Object.match (/home/depscloud/lib/service/unasyncify.js:14:59)
extractor_1  |     at handleUnary (/home/depscloud/node_modules/@grpc/grpc-js/build/src/server.js:425:13)
extractor_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
extractor_1  | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
extractor_1  | (node:17) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
extractor_1  |     at JSON.stringify (<anonymous>)
extractor_1  |     at Object.match (/home/depscloud/lib/service/unasyncify.js:14:59)
extractor_1  |     at handleUnary (/home/depscloud/node_modules/@grpc/grpc-js/build/src/server.js:425:13)
extractor_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
extractor_1  | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by mjpitz** [comment]
Discovered as part of: https://github.com/depscloud/deps.cloud/issues/33
