### ISSUE TITLE
Extractor is having issues loading protos from the API package

### ISSUE THREAD

**Issue by mjpitz** [depscloud/extractor#80]
```
Error: ENOENT: no such file or directory, open '/home/depscloud/node_modules/@depscloud/api/v1alpha/tracker/tracker.proto'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at fetch (/home/depscloud/node_modules/protobufjs/src/root.js:160:34)
    at Root.load (/home/depscloud/node_modules/protobufjs/src/root.js:194:13)
    at Root.loadSync (/home/depscloud/node_modules/protobufjs/src/root.js:235:17)
    at Object.loadSync (/home/depscloud/node_modules/@grpc/proto-loader/build/src/index.js:217:29)
    at Object.<anonymous> (/home/depscloud/node_modules/@depscloud/api/index.js:19:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by mjpitz** [comment]
This seems to be related to some of the proto-shifting I did when adding python support. Shouldn't be too hard to resolve and I suspect impact is pretty minimum.

**Comment by mjpitz** [comment]
`depscloud'/api#v0.1.10` pushed

**Comment by mjpitz** [comment]
Pushed `depscloud/extractor#v0.2.19`
